// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission04.Models;

namespace mission04.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    partial class MovieInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission04.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            category = "Action/Adventure",
                            director = "Peter Ramsey, Bob Persichetti, Rodney Rothman",
                            edited = false,
                            lent = "",
                            note = "",
                            rating = "PG",
                            title = "Spiderman:Into the Spider-Verse",
                            year = 2018
                        },
                        new
                        {
                            MovieId = 2,
                            category = "Drama",
                            director = "Frank Darabont",
                            edited = true,
                            lent = "",
                            note = "",
                            rating = "R",
                            title = "Shawshank Redemption, The",
                            year = 1994
                        },
                        new
                        {
                            MovieId = 3,
                            category = "Family",
                            director = "Lee Unkrich",
                            edited = false,
                            lent = "",
                            note = "",
                            rating = "G",
                            title = "Toy Story 3",
                            year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
