// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission04.Models;

namespace mission04.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    partial class MovieInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("mission04.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Action/Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Family"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Television"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "VHS"
                        });
                });

            modelBuilder.Entity("mission04.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("note")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            director = "Peter Ramsey, Bob Persichetti, Rodney Rothman",
                            edited = false,
                            lent = "",
                            note = "",
                            rating = "PG",
                            title = "Spiderman:Into the Spider-Verse",
                            year = 2018
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 2,
                            director = "Frank Darabont",
                            edited = true,
                            lent = "",
                            note = "",
                            rating = "R",
                            title = "Shawshank Redemption, The",
                            year = 1994
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 3,
                            director = "Lee Unkrich",
                            edited = false,
                            lent = "",
                            note = "",
                            rating = "G",
                            title = "Toy Story 3",
                            year = 2010
                        });
                });

            modelBuilder.Entity("mission04.Models.MovieResponse", b =>
                {
                    b.HasOne("mission04.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
